### ISSUE TITLE
Write access to Test-Results wiki

### ISSUE THREAD

**Issue by darincomeau** [CICE-Consortium/Test-Results#1]
I ran an Icepack testsuite on LANL IC (wolf) following the documentation (http://cice-consortium-icepack.readthedocs.io/en/master/user_guide/ug_testing.html#test-reporting). The documentation does indicate that I'll need write access to the wiki in order to report the results, and when trying to report, I get an authentication error:

Icepack/testsuite.v01a $ ./report_results.csh
Initialized empty Git repository in /turquoise/usr/projects/climate/dcomeau/Icepack/testsuite.v01a/Test-Results.wiki/.git/
error: Couldn't resolve proxy 'proxy/server' while accessing https://github.com/CICE-Consortium/Test-Results.wiki.git/info/refs

fatal: HTTP request failed
./report_results.csh: writing to Test-Results.wiki/icepack_master/34224289af.wolf.intel.180807.155648.md
[master 04ec1a9] update 34224289affc597bd49cdbc03465dadf90f65659 wolf
 5 files changed, 63 insertions(+), 0 deletions(-)
 create mode 100644 testsuite.v01a/Test-Results.wiki/icepack_master/34224289af.wolf.intel.180807.155648.md
 create mode 100644 testsuite.v01a/Test-Results.wiki/icepack_master/icepack_by_bran.md
 create mode 100644 testsuite.v01a/Test-Results.wiki/icepack_master/icepack_by_hash.md
 create mode 100644 testsuite.v01a/Test-Results.wiki/icepack_master/icepack_by_mach.md
 create mode 100644 testsuite.v01a/Test-Results.wiki/icepack_master/icepack_by_vers.md
ERROR: Permission to CICE-Consortium/Icepack.git denied to darincomeau.
fatal: The remote end hung up unexpectedly

**Comment by eclare108213** [comment]
I asked @darincomeau to try this, since we were unsure about it during our last meeting.  This issue might not require any action except to either confirm that this is the way we want it, or possibly to decide how to change it:  external users can not write to the test-results wiki without first getting access from the Consortium.  If we leave it this way, then we need to make sure we know what the process is for getting that access -- who they ask, who reviews the request, who makes the change in permissions, etc.

**Comment by apcraig** [comment]
I have created a new team, TestResultsWrite that will allow us to add anyone we want to that team to provide write permission to the Test-Results wiki.  For now, just @apcraig, @eclare108213, @duvivier, and @dabail10 are on that team and we already had write permission due to our status in the consortium, but adding the team allows us to quickly add others in the future as needed.  I will close this issue.
